"""Existing AUTO67 operator view; renders only bounded snapshots."""


DASHBOARD_HTML = """<!doctype html>
<meta charset="utf-8"><title>AUTO67 Live RE</title>
<style>body{font:14px sans-serif;background:#101418;color:#e8eef2;margin:20px}h1{margin:0 0 8px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.card{background:#1b232b;padding:10px;border-radius:6px}.workers{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:10px}.worker{border:1px solid #42525f;padding:6px;border-radius:4px}.WORKING,.CAPTURING,.HUNTING{border-color:#54d68a}.LEASED,.QUICK_CHECK{border-color:#f6c85f}.IDLE{border-color:#71808c}pre{white-space:pre-wrap}</style>
<h1>AUTO67 Live Opportunistic RE</h1><div id="summary">waiting for snapshot</div><div class="grid" id="cards"></div><h2>Workers</h2><div class="workers" id="workers"></div><h2>Capsules (bounded, no raw-event backlog)</h2><pre id="capsules"></pre><h2>Dispatch decisions</h2><pre id="decisions"></pre><h2>Observed history (last 24 transitions per worker)</h2><pre id="transitions"></pre><h2>Recent investigations (16)</h2><pre id="investigations"></pre>
<script>
async function refresh(){const s=await (await fetch('/api/status',{cache:'no-store'})).json();const d=s.dispatcher||{},m=d.metrics||{},l=s.lua||{};
document.getElementById('summary').textContent=`frame ${s.frame||0} epoch ${l.epoch||1} | capture events ${l.events_observed||0} | window ${d.rolling_window?.utilization||0}/${d.rolling_window?.capacity||0} | raw backlog ${s.raw_event_backlog_structure||'unknown'}`;
const p=d.dispatch_profile||{}, total=p.stages_us?.T0_T8_dispatch_to_worker_start_us||{}, lock=p.claim_lock_us||{}, ft=l.frame_timing||{}, hm=l.hook_metrics||{}, hf=hm.frames||{};
const fields=[['free workers',(m.workers_configured||0)-(m.workers_busy||0)],['busy workers',m.workers_busy||0],['event rate/s',m.event_rate||0],['novelty rate/s',m.recent_novelty_rate||0],['leases',m.worker_leases||0],['returns',m.worker_returns||0],['hunt attempts',m.hunt_attempts||0],['hunt successes',m.hunt_successes||0],['fresh candidates',m.fresh_candidates_available||0],['focused requested/waited',(m.focused_capture_requested||0)+'/'+(m.focused_capture_slot_waits||0)],['focused completed',m.focused_capture_completed||0],['hooks active',hm.active_hooks||0],['callbacks/frame p95/max',(hf.callbacks_per_frame?.p95||0)+'/'+(hf.callbacks_per_frame?.max||0)],['callback us/frame p95/max',(hf.callback_self_time_us_per_frame?.p95||0)+'/'+(hf.callback_self_time_us_per_frame?.max||0)],['known complete rejected',m.known_rejected_before_dispatch||0],['known by worker',m.known_found_during_work||0],['collision total',m.active_collisions||0],['merges before dispatch',m.investigation_merges||0],['new chains',m.new_chains||0],['new branches',m.new_branches||0],['new edges',m.new_edges||0],['window overwrites',l.events_overwritten||0],['avg seed age/s',m.average_seed_age||0],['max seed age/s',m.max_seed_age||0],['dispatch T0-T8 us p50/p95/max',(total.p50||0)+'/'+(total.p95||0)+'/'+(total.max||0)],['claim lock us p95/max',(lock.p95||0)+'/'+(lock.max||0)],['frame spikes >16/>33/>50ms',(ft.over_16ms||0)+'/'+(ft.over_33ms||0)+'/'+(ft.over_50ms||0)],['capsules',d.capsules?.configured||0],['free capsules',d.capsules?.capsules_free||0],['live captures',(d.capsules?.active_live||0)+'/'+(d.capsules?.max_simultaneous_live||0)],['capsules reused',d.capsules?.metrics?.capsules_reused||0],['raw backlog',s.raw_event_backlog_structure||'unknown'],['capture policy',l.sampling_policy||'unknown']];
document.getElementById('cards').innerHTML=fields.map(x=>`<div class="card"><b>${x[0]}</b><br>${x[1]}</div>`).join('');
document.getElementById('workers').innerHTML=(d.workers||[]).map(w=>`<div class="worker ${w.state}"><b>W${w.worker_id}</b> ${w.state}<br>${w.investigation_id||'-'}<br>stage ${w.stage}<br>age ${(w.seed_age||0).toFixed(3)}s<br>result ${w.last_result||'-'}</div>`).join('');
document.getElementById('capsules').textContent=(d.capsules?.items||[]).map(c=>`C${String(c.capsule_id).padStart(2,'0')} ${c.state} W${c.worker_id??'-'} ${(c.bytes_used/1024).toFixed(1)}KiB/${(c.capacity/1024).toFixed(0)} result ${c.freeze_reason||'-'}`).join('\n');
document.getElementById('decisions').textContent=JSON.stringify(m.dispatch_reasons||{},null,2)+(m.dispatch_starved_no_free_capsule?'\nDISPATCH_STARVED_NO_FREE_CAPSULE':'');
document.getElementById('transitions').textContent=(d.workers||[]).flatMap(w=>(w.transitions||[]).map(t=>({w:w.worker_id,...t}))).sort((a,b)=>b.at-a.at).map(t=>`${new Date(t.at*1000).toISOString().slice(11,23)} W${t.w} ${t.state} / ${t.stage} ${(t.chain||'-').slice(0,12)}`).join('\n');
document.getElementById('investigations').textContent=JSON.stringify((d.investigations||[]).slice(-16),null,2);}
async function poll(){try{await refresh();}catch(e){document.getElementById('summary').textContent='Snapshot unavailable / stale';}finally{setTimeout(poll,250);}}poll();
</script>"""
