set(OASIS_RE_TOOLING_SOURCES
    src/tools/gpgx_import_io.cpp
    src/tools/gpgx_json.cpp
    src/tools/re_slice_decoder.cpp
    src/tools/re_slice_flow_target.cpp
    src/tools/re_slice_exact.cpp
    src/tools/re_assemble.cpp
    src/tools/re_assemble_format.cpp
    src/tools/re_slice_format.cpp
    src/tools/re_program.cpp
    src/tools/re_program_format.cpp
    src/tools/re_trace.cpp
    src/tools/re_trace_format.cpp
    src/tools/re_diff.cpp
    src/tools/re_diff_detail.cpp
    src/tools/re_diff_format.cpp
    src/tools/re_atlas.cpp
    src/tools/re_atlas_format.cpp
    src/tools/re_atlas_ranking.cpp
    src/tools/re_resolution.cpp
    src/tools/re_resolution_format.cpp
    src/tools/re_cfg_audit.cpp
    src/tools/re_cfg_audit_format.cpp
    src/tools/re_reachable_closure.cpp
    src/tools/re_reachable_closure_format.cpp
    src/tools/re_reachable_stack.cpp
    src/tools/re_callee_effect.cpp
    src/tools/re_callee_effect_format.cpp
    src/tools/re_caller_stack.cpp
    src/tools/re_caller_stack_format.cpp
    src/tools/re_emulator_trace.cpp
    src/tools/re_emulator_trace_format.cpp
    src/tools/re_scenario.cpp
    src/tools/re_candidate_map.cpp
    src/tools/re_candidate_map_parse.cpp
    src/tools/re_candidate_map_format.cpp
    src/tools/re_mass_verify.cpp
    src/tools/re_mass_verify_format.cpp
    src/tools/re_explore.cpp
    src/tools/re_explore_format.cpp
    src/tools/re_explore_dynamic.cpp
    src/tools/re_ant.cpp
    src/tools/re_ant_format.cpp
    src/tools/re_ant_queue.cpp
    src/tools/re_ant_queue_format.cpp
    src/tools/re_static_translation.cpp
)
